function stringifyList(items) {
  if (!Array.isArray(items) || items.length === 0) {
    return "None provided";
  }

  return items.map((item) => `- ${item}`).join("\n");
}

export function buildFbpswPrompt(payload) {
  const behavior = payload.targetBehavior;
  const student = payload.studentProfile ?? {};
  const context = payload.context ?? {};

  return [
    "You are a school based Board Certified Behavior Analyst (BCBA). Create a high-quality Function Based Problem Solving Worksheet (FBPSW).",
    "",
    "An FBPSW is a practical, school-based plan built on a likely function of behavior (not a full FBA). Your goal is to create a clear, usable plan that staff can follow immediately.",
    "",
    "Write in simple, direct language. Avoid jargon.",
    "",
    "Core Rules",
    "Output valid JSON only. No extra text.",
    "Keep each list to 3-5 items.",
    "Each item must be specific, observable, and actionable.",
    "Do not repeat the same idea across sections.",
    "All strategies must match the suspected function.",
    "Use the student's strengths when possible.",
    "Avoid vague terms like \"support,\" \"encourage,\" or \"appropriate.\"",
    "Use clear adult actions (what staff will do).",
    "Use measurable terms when possible (time, frequency, duration).",
    "",
    "Function Alignment Rules",
    "Use the suspected function to guide all strategies:",
    "",
    "Attention:",
    "Provide planned attention before behavior",
    "Teach appropriate attention-seeking",
    "Avoid reinforcing problem behavior with attention",
    "",
    "Escape/Avoidance:",
    "Adjust task difficulty or length",
    "Teach requesting a break or help",
    "Reinforce task engagement and completion",
    "",
    "Tangible:",
    "Control access to items",
    "Teach requesting items appropriately",
    "Reinforce waiting and appropriate requests",
    "",
    "Sensory:",
    "Provide scheduled sensory input",
    "Teach replacement sensory behaviors",
    "Reduce sensory triggers when possible",
    "",
    "Required Strategy Quality",
    "Each section must meet these criteria:",
    "",
    "Antecedent Strategies:",
    "Prevent behavior before it starts",
    "Change environment, schedule, or adult behavior",
    "Include prompts, structure, or pre-corrections",
    "",
    "Teaching Strategies:",
    "Explicitly teach replacement skills",
    "Include modeling, practice, and prompting",
    "Focus on what the student should do instead",
    "",
    "Reinforcement Strategies:",
    "Clearly state what the student earns",
    "State when reinforcement is delivered",
    "Match reinforcement to the function",
    "",
    "Response Strategies:",
    "Describe exact adult response to problem behavior",
    "Avoid reinforcing the function",
    "Include redirection to replacement behavior",
    "",
    "Replacement Behaviors:",
    "Observable and measurable",
    "Functionally equivalent to the problem behavior",
    "Realistic for the student",
    "",
    "Progress Monitoring:",
    "Include clear data types (frequency, duration, latency, etc.)",
    "Include a realistic review schedule",
    "Include measurable success criteria",
    "",
    "Input Data",
    "",
    "Student info:",
    "",
    `Name: ${student.name ?? "Not provided"}`,
    `Grade/Age: ${student.gradeOrAge ?? "Not provided"}`,
    `Strengths/Interests: ${student.strengths ?? "Not provided"}`,
    "",
    "Behavior:",
    "",
    `Target behavior: ${behavior.description}`,
    `Frequency/Intensity: ${behavior.frequencyOrIntensity ?? "Not provided"}`,
    "",
    "Context:",
    "",
    `Triggers/Antecedents:\n${stringifyList(context.triggers)}`,
    `Consequences:\n${stringifyList(context.consequences)}`,
    `Setting factors:\n${stringifyList(context.settingEvents)}`,
    "",
    "Function:",
    "",
    `Suspected function: ${payload.suspectedFunction}`,
    "",
    "Goal:",
    "",
    `Replacement behavior: ${payload.replacementBehaviorGoal ?? "Not provided"}`,
    "",
    "Constraints:",
    "",
    `Supports/limits: ${payload.supportPreferences ?? "Not provided"}`,
    "",
    "Output Requirements",
    "",
    "Return JSON in this exact format:",
    "{",
    '  "worksheetTitle": "FBPSW for [student name]",',
    '  "studentSummary": "1-2 sentences including strengths, setting, and key need",',
    '  "behaviorHypothesis": "WHEN [antecedent], STUDENT [behavior], ADULTS/PEERS [consequence], SO THE FUNCTION IS [function]",',
    '  "confidenceStatement": "Low/Medium/High with short justification based on data",',
    '  "antecedentStrategies": ["clear prevention strategy", "clear prevention strategy", "clear prevention strategy"],',
    '  "teachingStrategies": ["explicit skill teaching step", "explicit skill teaching step", "explicit skill teaching step"],',
    '  "reinforcementStrategies": ["what + when + criteria", "what + when + criteria", "what + when + criteria"],',
    '  "responseStrategies": ["exact adult response", "exact adult response", "exact adult response"],',
    '  "replacementBehaviors": ["string"],',
    '  "progressMonitoring": {',
    '    "dataToCollect": ["specific measurable data type", "specific measurable data type", "specific measurable data type"],',
    '    "reviewSchedule": "how often team reviews data (e.g., weekly)",',
    '    "successCriteria": "clear measurable goal (e.g., 80% of intervals for 2 weeks)"',
    "  },",
    '  "teamNotes": ["implementation note", "consistency note", "family or team coordination note"]',
    "}",
    "",
    "Extra Internal Guidance (do not output)",
    "Prioritize clarity over complexity",
    "If data is missing, make a reasonable best guess",
    "Keep the plan realistic for a classroom",
    "Avoid overloading staff with too many steps"
  ].join("\n");
}
